# Artifact repository MinIO/S3 for Workflows in this namespace.
# endpoint = hostname only (sans https://) ; insecure=false pour TLS.
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: workflows-argo
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    s3:
      bucket: argo-workflows
      endpoint: minios3.alexetnico.com
      insecure: false
      accessKeySecret:
        name: minio-artifacts
        key: accessKey
      secretKeySecret:
        name: minio-artifacts
        key: secretKey
