apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello
  namespace: workflows-argo
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine:3.20
        command: [echo, "hello from WorkflowsArgo"]
