apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello
  namespace: workflows-argo
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  archiveLogs: true
  podGC:
    strategy: OnPodSuccess
  ttlStrategy:
    secondsAfterSuccess: 86400
    secondsAfterFailure: 259200
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  templates:
    - name: main
      container:
        image: alpine:3.20
        command: [echo, "hello from WorkflowsArgo"]
